name: Release new versions
on:
  push:
    tags:
      - '*'
jobs:
  generate-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: 'pip'

    - name: Install build tools
      run: python -m pip install build

    - name: Build the package
      run: python -m build

    - name: Create Release
      run: |
        gh release create "${{ github.ref_name }}" -t "Release ${{ github.ref_name }}" dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: Publish to PyPI
    needs:
    - generate-release
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/compress_comics
    permissions:
      id-token: write
    steps:
    - name: Download the built files
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish the distributions
      uses: pypa/gh-action-pypi-publish@release/v1
